- name: Provision EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: docker-host
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        state: running
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        network:
          assign_public_ip: true
        tags:
          Environment: DockerServer
      register: ec2

    - name: Add new instance to dynamic inventory
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: ec2_hosts
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        delay: 30
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"
